export const SCENE_KEYS = Object.freeze({
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    MAIN_MENU_SCENE: 'MAIN_MENU_SCENE',
    WORLD_SCENE: 'WORLD_SCENE',
    UI_SCENE: 'UI_SCENE',
    HOW_TO_PLAY_SCENE: 'HOW_TO_PLAY_SCENE'
})

